<?php
/**
 * Created by PhpStorm.
 * User: information
 * Date: 2017/11/28
 * Time: 上午9:23
 */
namespace app\api\controller;

use app\common\lib\exception\ApiException;
use think\Cache;
use think\Controller;

class Common extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkSignAuth();
    }
    public function checkSignAuth(){
        $param = input('param.');
        $header = request()->header();

        if (empty($header['sign'])){
            throw new ApiException('缺少sign',400);
        }
        if (empty($header['time'])){
            throw new ApiException('缺少time',400);
        }
        if (empty($header['did'])){
            throw new ApiException('缺少did',400);
        }
        $param['time'] = $header['time'];
        $param['did'] = $header['did'];
        ksort($param);
        $str = http_build_query($param);
        $str1 = md5($str);
        $str2 = strtoupper($str1);
        $str3 = $str2 . config('app.md5_code');
        $str4 = md5($str3);
        if ($str4 != request()->header('sign')){
            throw new ApiException('认证失败',401);
        }
        if (time() - $header['time'] > config('app.sign_time')){
            throw new ApiException('签名认证超时');
        }
        if (Cache::get($header['sign'])){
            throw new ApiException('签名不具备唯一性',401);
        }
        Cache::set($header['sign'],'1',config('app.sign_cache_time'));
    }

}