<?php
/**
 * Created by PhpStorm.
 * User: information
 * Date: 2017/11/29
 * Time: 上午8:45
 */
namespace app\api\controller;

use think\Controller;

class Common extends Controller{
    //自动调用验证
    protected function _initialize()
    {
        $this->checkSign();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //验证sign
    public function checkSign(){
        //判断头部信息是否都有
        $header = request()->header();
        if (empty($header['sign'])){
            throw new ApiException('缺少sign',400);
        }
        if (empty($header['time'])){
            throw new ApiException('缺少time',400);
        }
        if (empty($header['did'])){
            throw new ApiException('缺少did',400);
        }
        $param = input('param.');
        $param['time'] = $header['time'];
        $param['did'] = $header['did'];
        ksort($param);
        $str = md5(strtoupper(md5(http_build_query($param))) . 'app.md5_code');
        
    }
}